[build]
  command = "yarn run build"
  functions = "./functions-build"
  publish = "./build"

[template.environment]
  FAUNADB_SECRET = "Your FaunaDB Server Secret"
  USER_LOGIN = "Your User Password"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
